kind: pipeline  
name: deploy  
  
steps:  
  - name: unit-test  
    image: node:10  
    commands:  
      - node test/index.js  
    when:  
      branch: master  
      event: push  
 
  - name: build-image  
    image: plugins/docker  
    settings:  
      repo: keifuku123/drone-ci-demo  
      username: keifuku123 
      password:  
        from_secret: DOCKER_PASSWORD  
      auto_tag: true  
    when:  
      event: tag
          
  - name: k8s-deploy  
    image: quay.io/honestbee/drone-kubernetes  
    settings:  
      kubernetes_server:  
        from_secret: KUBERNETES_SERVER  
      kubernetes_cert:  
        from_secret: KUBERNETES_CERT  
      kubernetes_token:  
        from_secret: KUBERNETES_TOKEN  
      namespace: default  
      deployment: ci-demo-deployment  
      repo: keifuku123/drone-ci-demo  
      container: ci-demo  
      tag:  
        - ${DRONE_TAG}  
    when:  
      event: tag
